### ISSUE TITLE
querier configmap name is not changed to the configmapgenerator name when using index-gateway

### ISSUE THREAD

**Issue by RyanSquared** [BitGo/kustomize-loki#27]
When building this kustomization with the index gateway enabled, the querier's volume for the configmap just says "loki", not "loki-b99h6c8m6b". This was built with Kustomize version 4.2.0. Has anyone encountered this, or knows a fix?

**Comment by RyanSquared** [comment]
I'm guessing this is an issue with kustomize but I'm assuming because the code was merged here that there's something I might be missing, like a fix to kustomize.

**Comment by james-callahan** [comment]
https://github.com/kubernetes-sigs/kustomize/issues/4136
