### ISSUE TITLE
Upgrade to loki 2.7.0

### ISSUE THREAD

**Issue by james-callahan** [BitGo/kustomize-loki#66]
https://github.com/grafana/loki/releases/tag/v2.7.0
https://grafana.com/docs/loki/next/upgrading/#270

Notable changes:
  - https://grafana.com/docs/loki/next/upgrading/#engine-query-timeout-is-deprecated indicates we may need to change `LOKI_QUERIER_QUERY_TIMEOUT` and/or `LOKI_QUERIER_ENGINE_TIMEOUT`

**Comment by therealdwright** [comment]
Closed via #70
